### ISSUE TITLE
fastText support tracking issue

### ISSUE THREAD

**Issue by danieldk** [finalfusion/finalfusion-rust#27]
This issue is for tracking addition of reading functionality for fastText embeddings.

- [x] Modify subword handling to support different indexers. PR: #25
- [x] Add constuctor trait for bucketing indexers. PR: #28 
- [x] Add `FastTextIndexer`. PR: #29
- [x] Modify `SubwordVocab` to be generic over the indexer. PR: #30 
- [x] Add support for fastText-derived vocabularies to `SubwordVocab`. PR: #31 
- [x] Add and implement `FastTextReader` trait. PR: #32 
- [x] Update `finalfusion-utils` to support the fastText file format.
- [x] Add static method to `finalfusion-python` to read fastText embeddings.
- [x] Add unit tests for reading fastText with a toy file.

@sebpuetz I added you as an assignee for the reviewing. I have nearly all functionality implemented already.

**Comment by sebpuetz** [comment]
Just reviewed the first part. This will also make it rather straight forward to add other kinds of subword vocabs, which is nice ;)

**Comment by danieldk** [comment]
> Just reviewed the first part. This will also make it rather straight forward to add other kinds of subword vocabs, which is nice ;)

Indeed. Once the `Vocab` changes were in, adding fastText subword vocab support was mostly a matter of adding another chunk identifier for serialization/deserialization.
